apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app
  namespace: argocd
spec:
  project: neo-platform
  source:
    repoURL: git@github.com:yutthasard-kkp/idp-app.git
    targetRevision: main
    path: platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: neo-platform
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true