apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nonprod-payment-service
  namespace: argocd
spec:
  project: neo-platform
  source:
    repoURL: git@github.com:yutthasard-kkp/nonprod-k8s-manifests.git
    targetRevision: main
    path: dev/neo-platform/payment-service
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod-neo-platform
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true