apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
	g, nongkai, proj:payment:read-write
    g, nongkai, proj:kyc:read-only
    g, nongped, proj:kyc:read-write
    p, pukjee, applications, *, */*, allow
    p, pukjee, projects, get, *, allow