apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kyc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Team Kyc
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  roles:
    - description: Read Only
      name: read-only
      policies:
        - p, proj:kyc:read-only, applications, get, kyc/*, allow
    - description: Read Write
      name: read-write
      policies:
        - p, proj:kyc:read-write, applications, get, kyc/*, allow
        - p, proj:kyc:read-write, applications, sync, kyc/*, allow
        - p, proj:kyc:read-write, applications, update, kyc/*, allow
  sourceRepos:
    - git@github.com:yutthasard-kkp/nonprod-k8s-config.git
    - git@github.com:yutthasard-kkp/nonprod-k8s-manifests.git